steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform && terraform init --backend-config="bucket=$REPO_NAME-$PROJECT_ID-tfstate"

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd terraform && terraform plan -var="project_id=$PROJECT_ID" -var="service_account_email=$PROJECT_ID-compute@developer.gserviceaccount.com"
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd terraform && terraform apply -var="project_id=$PROJECT_ID" -var="service_account_email=$PROJECT_ID-compute@developer.gserviceaccount.com"
# [END tf-apply]      
#Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME-image:${BUILD_ID}'
    - '-t'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME-image:latest'
    - '.'
#Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME-image'
    - '--all-tags'