steps:
#Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_FULL_IMAGE_NAME}:$GITHUB_SHA'
    - '-t'
    - '${_FULL_IMAGE_NAME}:latest'
    - '.'
#Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_FULL_IMAGE_NAME}'
    - '--all-tags'
substitutions:
    _IMAGE: 'mms-cloud-skeleton-image'
    _FULL_IMAGE_NAME: 'error'
    _GITHUB_SHA: 'SHA'
options:
    dynamic_substitutions: true