steps:
#Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_FULL_IMAGE_NAME}:$COMMIT_SHA'
    - '-t'
    - '${_FULL_IMAGE_NAME}:latest'
    - '.'
#Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_FULL_IMAGE_NAME}'
    - '--all-tags'
substitutions:
    _FULL_IMAGE_NAME: 'error'
options:
    dynamic_substitutions: true